MANIFEST.in, README.md, idc_index/index.py, setup.py
To address #3, 
s5cmd and index_csv are now downloaded during pip installation
=> install idc_index and s5cmd binary during pip installation

idc_index/index.py, setup.py
* switch the source of CSV to idc-index release
* add SeriesInstanceUID to the download_from_selection() for completeness
* fix indentation
* correct conversion (GiB is pow(2), GB is pow(10))
* bump the release to 0.2.4
=> Various minor refinements

idc_index/index.py, setup.py, tests/idcindex.py
also:
* added corresponding test
* added loading of the index from the URL when local file is not found
* added detection of local s5cmd if not found where expected, and error handling
=> add sql_query() call to query the index

idc_index/index.py, setup.py
re #27:
* do not catch exception if file is not available in the setup step
* inform the user about downloading index in the constructor
* save index when downloading in the constructor so it is not re-downloaded
=> revisit steps related to packaging and index download

idc_index/index.py
Explicitly search for the `s5cmd` executable and raise a more informative `FileNotFoundError` exception if not found, replacing the generic `ValueError`. Use "check_call" to confirm that the found `s5cmd` executable accepts `--help` without displaying its output.
Revise logging messages for clarity:
```
$ python -c 'import logging; logging.basicConfig(level=logging.DEBUG); from idc_index import index; client = index.IDCClient()'
WARNING:idc_index.index:Index file not found. Downloading version 0.2.11 of the index file. This will take a minute or so.
WARNING:idc_index.index:Index file v0.2.11 downloaded.
DEBUG:idc_index.index:Reading index file v0.2.11
DEBUG:idc_index.index:Found s5cmd executable: /path/to/bin/s5cmd
```
=> fix: Improve s5cmd lookup and error reporting

idc_index/index.py
Also convert functions to be static methods and rename parameters to be more descriptive.
=> chore: Refactor IDCClient filtering helper functions de-duplicating logic

tests/idcindex.py
=> BUG: fix path to the manifests used by tests

idc_index/index.py, pyproject.toml, tests/idcindex.py
=> enh: add functionality to generate the list of citations for the selection

README.md
thanks to @oohtmeel1 for reporting the error.
This PR fixes #92 by correcting the download instructions in the README.md file
=> fix: convert the array to list in download instructions

CONTRIBUTING.md, pyproject.toml
Based on https://github.com/Slicer/Slicer/blob/main/CONTRIBUTING.md
=> enh: add contributing guidelines

idc_index/index.py, pyproject.toml, tests/idcindex.py
Aims to address #100 partially
=> feat: enable downloading data from previous idc data versions

idc_index/index.py
=> ENH: fix error messages for items not identified in the current version

idc_index/index.py, tests/idcindex.py
also added checks for existence of the URLs containing remote indices
=> ENH: add clinical_index

idc_index/cli.py, idc_index/index.py
Automatic creation of the destination directory mimics the behavior of s5cmd and simplifies usage
=> ENH: simplify download and create destination directory if needed

pyproject.toml
This will add values column to the clinical_index
=> ENH: update to idc-index-data 19.0.2

README.md, docs/column_descriptions.md
=> DOC: fix broken links

idc_index/index.py, tests/idcindex.py
=> ENH: support selection of gcs for manifest creation

idc_index/index.py
Due to the switch from `public-datasets-idc` to `idc-open-data` bucket for GCS, the logic for detecting provider from s3_url had to be updated.
In the situations where manifest contains a mix of URLs between `idc-open-data` and other buckets within the same provider, the prior logic would fail since `idc-open-data` URLs would match those in AWS, but other URLs would not, and the code would incorrectly conclude that the manifest contains a mix of URLs across more than one provider.
In the updated code, URLs that refer to `idc-open-data` are ignored, and the assessment of whether there is more than one endpoint is done for the remaining URLs. Also, while mapping manifest URLs from AWS to GCP, mapping of `idc-open-data` is not done, `public-datasets-idc` has been replaced with …
=> BUG: fix download of GCS manifest based content

idc_index/index.py, pyproject.toml, tests/idcindex.py
Revisited how duckdb queries are done, updated version of duckdb, updated numpy to the latest to fix the Colab runtime error regression, fix some bugs on the way, added new test.
Re #125
=> Update to use newer duckdb and update numpy

idc_index/index.py, tests/idcindex.py
Fix for #168 as suggected in that issue
=> Google source bucket fix
