- idc_index/index.py
s5cmd output redirect appears to cause troubles in some situations
> do not try to capture output in quiet mode

- idc_index/index.py
- queries/idc_index.sql
- setup.py
- tests/idcindex.py
- tests/study_manifest_aws.s5cmd
- tests/study_manifest_gcs.s5cmd
* use dedicated logger
* improve manifest download function to identify the right endpoint and support destination directory to address #17
* keep IDC version in a variable
* reorganize the query to be consistent with the comments and use bucket column
> Update to v17, make manifest download more robust, and other refinements

- pyproject.toml
Following the release of duckdb 0.10.0 supporting Python 3.12, there is no need to install different version depending on the Python version being used.
Follow-up of https://github.com/ImagingDataCommons/idc-index/commit/ac9705cb99de8d72bd96e372f8db464062551160
```
fix: Support Python 3.12 adding dependency to duckdb pre-release
Since the latest regular release of duckdb does not project Python 3.12
wheels, we install the latest pre-release when Python 3.12 is used.
> fix: Simplify duckdb dependency

- idc_index/index.py
To conveniently support python environment with an incorrectly setup PATH (e.g https://github.com/Slicer/Slicer/pull/7587), this commit adds a dedicated workaround.
> fix: Simplify lookup of s5cmd and improve associated comments

- README.md
- pyproject.toml
I am excluding .md files, since it is not clear to me if `ruff` is even able to check Markdown, and if yes - how it should be configured. Without this commit, `ruff` precommit checks fail with messages that do not make sense:
```
error: Failed to parse README.md:3:2: Unexpected token '!'
README.md:3:2: E999 SyntaxError: Unexpected token '!'
Found 1 error.
```
Based on my searches and an [exchange with Perplexity](https://www.perplexity.ai/search/I-am-using-xEPxl6cpROe6DLfnpSGkMA?s=c), I did not find a way to solve this other than disable Markdown in `ruff` configuration.
> exclude .md files from ruff and fix formatting

- .github/workflows/keep-alive.yaml
Provided write permission, uses GitHub api to keep the gha alive instead of creating an empty commit
Since the behavior is erratic (working fine on some IDC repos and does not on others), I did not test this on my fork
> Debug keep-alive gh action

- idc_index/index.py
- pyproject.toml
@fedorov Once https://github.com/ImagingDataCommons/idc-index-data/pull/17 is merged, and new pypi release is created,
I'll lock the data version in idc-index's pyproject.toml. This PR should then pass the tests.
> Switch index to parquet format

- pyproject.toml
Once idc-index-data to v18.0.0, we can create a new release.
> bump idc-index-data to v18

- idc_index/index.py
addresses #66
s5cmd ls sometimes returns directories as well, this update ensures only .dcm links are returned
> fix: return only .dcm links 

- .github/workflows/ci.yml
- idc_index/index.py
- pyproject.toml
- tests/idcindex.py
- tests/study_manifest_aws.s5cmd
- tests/study_manifest_bogus.s5cmd
- tests/study_manifest_gcs.s5cmd
This PR aims to address #24 and #51
there is no way to track download sequentially as s5cmd run or cp command will be locked on a thread. so, download progress is outsourced to a thread and will run simultaneously along side download thread on both series and manifest downloader
as the index only contains aws urls, when a manifest contains gcs urls, crdc series instance uuid is extracted from aws urls and queried against the aws urls in the index to get download size. For manifest download, download size is calculated first and the progress is tracked against as a whole.
manifest validator in download from manifest is offloaded to a dedicated function that will check not only the first line but every line, and if the manifest has urls from both gcp and aws to raise an exception.
s5cmd cp …
> feat: report download progress

- idc_index/index.py
- tests/idcindex.py
addresses #22 
Default template directory is "%collection_id/%PatientID/%Modality/%StudyInstanceUID/%SeriesInstanceUID" However a user can pick and choose any of these five attributes in any order. In addition, the attributes can also be concatenated using hyphens or underscores. But attributes must begin with a percentage sign.
> enh: provide an option to download into a user defined hierarchy

- idc_index/index.py
- tests/idcindex.py
the logic for concatenating patient age and sex was not changed following the change in handling of nulls in PR #68
This PR addresses issue #76 and simplifies the handling of patients_df with the help of an sql query. All the get uuid functions are now tested with every combination possible to increase the robustness.
Once this PR is merged and a new version is released, this should fix https://github.com/ImagingDataCommons/SlicerIDCBrowser/issues/36.
> bug(fix): fix get_patients

- idc_index/index.py
As I was testing the latest index.py on SlicerIDCBrowser, I noticed that no matter which collection I select, the same patients are shown. Found that this was of incorrect reference used in the SQL query of get_patients.
In addition, the same logic that plagued get_patients affects get_dicom_studies as well, when there are nulls in seriesDescriptions or dates.
This PR addresses both issues
> bug(fix): fix reference used in get patients sql query

- idc_index/index.py
`dry_run` parameter was ignored, and download was happening in either case.
> bug: fix behavior of dry_run for download operation

- README.md
- docs/index.md
Switch to use of GitHub markdown admonition
See https://github.com/orgs/community/discussions/16925
| Before |After |
|--|--|
| ![image](https://github.com/ImagingDataCommons/idc-index/assets/219043/b29e57d7-357e-45c1-a2f2-eb26b8a1a27e) | ![image](https://github.com/ImagingDataCommons/idc-index/assets/219043/d579b47b-baae-47a2-bc15-ab7179d1084d) |
> doc: Improve rendering of "early development" notice in README

- idc_index/index.py
This is a follow-up of https://github.com/ImagingDataCommons/idc-index/pull/83
Update indentation to fix warnings like the following:
```
/path/to/index.py:docstring of idc_index.index.IDCClient.get_viewer_URL:1: WARNING: py:class reference target not found: available in
/path/to/index.py:docstring of idc_index.index.IDCClient.get_viewer_URL:1: WARNING: py:class reference target not found: or slim. If not
/path/to/index.py:docstring of idc_index.index.IDCClient.get_viewer_URL:1: WARNING: py:class reference target not found: default viewers will be
```
Fix the following warning using "list[str]" instead of "a list of str"
```
/path/to/index.py:docstring of idc_index.index.IDCClient.get_patients:1: WARNING: py:class reference target not found: a list
```
Remove the use of the "optional" …
> Additional API docstrings fixes

- idc_index/index.py
- tests/idcindex.py
while iterating over files to calculate downloaded file size, it is possible for a temp file created by s5cmd to be removed before we get its size; add handling of the exception if a file is not found
> bug: fix race condition

- idc_index/cli.py
- idc_index/index.py
- pyproject.toml
- tests/idcindex.py
addresses #33 
Supports download from selection or a manifest for now. Used 'idc' as 'binary' but can be configured to anything else.
I can not get tests to initialize but I did test on colab. I would appreciate it if anyone could work on completing the tests. If there are any examples, I can follow them.
> feat: provide a command line option to download from cli

- idc_index/index.py
Currently whenever a download path consists of spaces, s5cmd command does not work. 
But to force it, we must include the path containing spaces in double quotes. The issue was first encountered in SlicerIDCBrowser. https://github.com/ImagingDataCommons/SlicerIDCBrowser/issues/39
This PR will fix https://github.com/ImagingDataCommons/SlicerIDCBrowser/issues/39
> enh: add double quotes before paths so spaced paths can work

- idc_index/cli.py
- idc_index/index.py
- tests/idcindex.py
This should address most common usage scenario. 
Follow up on #33.
> enh: add zero parameter download cli

- idc_index/cli.py
This PR adds `--dir-template` option to the cli. The default value is the default template dir `IDCClient.DOWNLOAD_HIERARCHY_DEFAULT`.
To download all files into the download directory as specifie with `--download-dir` one may specify an empty template: `--dir-template ""`.
> feat: add --dir-template argument to cli entrypoints

- README.md
- idc_index/__init__.py
- idc_index/index.py
- tests/idcindex.py
No need for a global `client = IDCClient()` call, instead `IDCClient.client()` can be used directly. Upon first call a new IDCClient instance will be initialized and reused for all following calls.
> Add IDCClient() singleton feature

- idc_index/index.py
- tests/idcindex.py
- tests/prior_version_manifest.s5cmd
Re #100
Whenever a crdc_series_uuid from the manifest is not matched to those known to the index, provide error message informing the user of what could be the reasons. Fixed error checking for unrecognized items in the validation function. Report unrecognized items independently of whether validation is requested or not.
> ENH: improve error reporting for unrecognized items from the manifest

- idc_index/index.py
- tests/idcindex.py
I made a suggestion on how to implement 
- list_indices()
- fetch_index()
There is certainly room for improvement, but we can use it as basis for further discussion.
> list_indices and fetch_index implemented

- idc_index/index.py
- sql_query() requires setting the tables directly before the duckdb call. This was done here.
> BUG: fixed sql_query function to work with multiple indices

- idc_index/index.py
Addresses #115 
extraneous spaces throws off the s3 url comparison b/w manifest and index. While I did not investigate much further, this shows that https://github.com/ImagingDataCommons/idc-index/blob/main/idc_index/index.py#L808 is not robust enough, as the validation function was returning 'gcs' endpoint for aws urls.
> BUG: use trim to remove any extraneous spaces while parsing s3 url in manifest

- idc_index/index.py
SeriesInstanceUID changed to SeriesInstanceUIDs, see https://docs.ohif.org/migration-guide/from-3p7-to-3p8#studyinstanceuid-in-the-url-param
> BUG: fix viewer series selection parameter

- idc_index/index.py
- tests/idcindex.py
- tests/prior_version_manifest.s5cmd
completes #100 
- fixes and improves logic of s5cmd sync download by utilizing validation results 
- picks 5 smallest series from previous idc versions
- tests prior versions data rigorosly with all combinations of optional parameters
may be better to create a new issue to support this https://github.com/ImagingDataCommons/idc-index/issues/100#issuecomment-2264179846. So far I do not know an 'elegant' way to support it
> fix: s5cmd sync logic

- idc_index/cli.py
- idc_index/index.py
- tests/idcindex.py
> ENH: support download by crdc_series_uuid

- idc_index/index.py
- pyproject.toml
- tests/idcindex.py
Also address #107 by installing both indices and clinical_data into user directory instead of the python package location.
> ENH: download clinical data files if clinical_index is requested

- idc_index/cli.py
I like the simplified and generic interface of the idc function a lot @fedorov. As discussed a while ago, I added the cli options to specify a output directory and to overwrite (e.g., customize or flatten) the template structure, consistent with the other endpoints.
> add download dir and template arguments to generic idc program

- idc_index/index.py
This came up while trying to use manifests generated using Looker Studio
> BUG: ignore manifest lines that do not contain s3 URLs

- idc_index/index.py
- tests/study_manifest_aws.s5cmd
> BUG: catch another situation where invalid manifest lines were not handled

- .pre-commit-config.yaml
- docs/column_descriptions.md
- idc_index/__init__.py
- idc_index/cli.py
- idc_index/index.py
- pyproject.toml
This PR modernizes our linting/formatting toolchain and applies the minimal code/style edits needed to pass it. It also reintroduces safe checks we previously disabled (imports sorting) and adds schema validation for `pyproject.toml`.
**Ruff / config**
* CI: Remove blanket `# ruff: noqa` segments (fixes `PGH004`) and add explicit Ruff rule exceptions in `pyproject.toml`.
* CI: Drop unused pinned Ruff version from dev deps in `pyproject.toml`.
* CI: Reintroduce `"I"` (isort) checks.
**Code style & docs**
* STYLE: Normalize empty lines anticipating proper `noqa` usage.
* DOC: Rewrite docstrings to satisfy `pydocstyle` (e.g., D200, D415).
* STYLE: Prefer `is not` / `not in` forms (Ruff E714).
**pre-commit & validation**
* CI: Update pre-commit hooks to current releases; switch to maintained …
> CI/STYLE: Modernize Ruff & pre-commit; clean docstrings; remove blanket noqa; re-enable import sorting
